version: '3'
services:
  backend:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./downloads:/app/downloads

  frontend:
    image: nginx:alpine
    volumes:
      - ./frontend:/usr/share/nginx/html
    ports:
      - "8080:80"
